---
title: "Tutorials and Scripts"
output:
  prettydoc::html_pretty:
    theme: cayman
fontsize: 18pt
---

[Back to main page](index.html)

# List of Tutorials and scripts

**Intro**

1. 2023-08-30: [Bash Tutorial](Fall2023/tutorials/BashTutorial.html)
2. 2023-09-06: [Git Tutorial](Fall2023/tutorials/GithubTutorial_Csenge.html)

**Population & Landscape Genomics Module**

3. 2023-09-11: [PopGen Day 1](Fall2023/tutorials/2023-09-11_PopGenomics_Day1_v2.html)
4. 2023-09-13: [PopGen Day 2](Fall2023/tutorials/2023-09-13_PopGenomics_Day2.html)
5. 2023-09-18: [PopGen Day 3](Fall2023/tutorials/2023-09-18_PopGenomics_Day3.html)
6. 2023-09-20: [PopGen Day 4](Fall2023/tutorials/2023-09-20_PopGenomics_Day4.html)
7. 2023-09-25: [PopGen Day 5](Fall2023/tutorials/2023-09-25_PopGenomics_Day5.html)
8. 2023-09-27: [PopGen Day 6](Fall2023/tutorials/2023-09-27_PopGenomics_Day6.html)
9. 2023-10-02: [PopGen Day 7](Fall2023/tutorials/2023-10-02_PopGenomics_Day7.1.html)
10. 2023-10-04: [PopGen Day 8](Fall2023/tutorials/2023-10-04_PopGenomics_Day8.html)

**Transcriptomics Module**

11. 2023-10-09: [Transcriptomics Day 1](Fall2023/tutorials/2023-10-09_RNAseq_Day1v2.html)
12. 2023-10-11: [Transcriptomics Day 2](Fall2023/tutorials/2023-10-11_RNAseq_Day2.html)
13. 2023-10-16: [Transcriptomics Day 3](Fall2023/tutorials/2023-10-16_RNAseq_Day3.html)
14. 2023-10-18: [Transcriptomics Day 4](Fall2023/tutorials/2023-10-18_RNAseq_Day4.html)
15. 2023-10-23: [Transcriptomics Day 5](Fall2023/tutorials/2023-10-23_RNAseq_Day5.html)
16. 2023-10-25: [Transcriptomics Day 6](Fall2023/tutorials/2023-10-25_RNAseq_Day6.html)
17. 2023-10-30: [Transcriptomics Day 7](Fall2023/tutorials/2023-10-30_RNAseq_Day7.html)
18. 2023-11-01: [Transcriptomics Day 8](Fall2023/tutorials/2023-11-01_RNAseq_Day8.html)


**Structural Variation Module**

19. 2023-11-06 and 2023-11-08: [Structural Variation](Fall2023/tutorials/Csenge_structural_variation.html)

**2021**
1. 2021-12-16: [Github Tutorial](GithubTutorial2021.html)

**Microbiome Module**

1. 2021-09-13: [Microbiome tutorial day one](2021-09-13_microbiome_Day1.html)
2. 2021-09-15: [Microbiome tutorial day two](2021-09-15_microbiome_Day2.html)
3. 2021-09-20: [Microbiome tutorial day three](2021-09-20_microbiome_Day3.html)
4. 2021-09-22: [Microbiome tutorial day four](2021-09-22_microbiome_Day4.html)
5. 2021-09-27: [Microbiome tutorial day five](2021-09-27_microbiome_Day5.html), plus supplemental code for [taxonomic identification](2021_09_27_microbiome_supp_taxaID.html).

**RNAseq Module**

6. 2021-09-29: [RNAseq tutorial day one](2021-09-29_RNAseq_Day1.html)
7. 2021-10-04: [RNAseq tutorial day two](2021-10-04_RNAseq_Day2.html)
8. 2021-10-06: [RNAseq tutorial day three](2021-10-06_RNAseq_Day3.html)

9-10. 2021-10-12: [RNAseq tutorial days four and five](2021-10-11_RNAseq_Day4.html)

**Population Genomics**

11. 2021-10-18: [PopGen Day 1](2021-10-18_PopGenomics_Day1.html)
12. 2021-10-20: [PopGen Day 2](2021-10-20_PopGenomics_Day2.html)
13. 2021-10-25: [PopGen Day 3](2021-10-25_PopGenomics_Day3.html)
14. 2021-10-27: [PopGen Day 4](2021-10-27_PopGenomics_Day4.html)
15. 2021-11-01: [PopGen Day 5](2021-11-01_PopGenomics_Day5.html)
16. 2021-11-03: [PopGen Day 6](2021-11-03_PopGenomics_Day6 (1).html)
17. 2021-11-08: [PopGen Day 7](2021-11-08_PopGenomics_Day7 (1).html)
18. 2021-11-10: [PopGen Day 8](2021-11-010_PopGenomics_Day8.html)


**Microbiome Module**

1. 2021-09-13: [Microbiome tutorial day one](Fall2021/tutorials/2021-09-13_microbiome_Day1.html)
2. 2021-09-15: [Microbiome tutorial day two](Fall2021/tutorials/2021-09-15_microbiome_Day2.html)
3. 2021-09-20: [Microbiome tutorial day three](Fall2021/tutorials/2021-09-20_microbiome_Day3.html)
4. 2021-09-22: [Microbiome tutorial day four](Fall2021/tutorials/2021-09-22_microbiome_Day4.html)
5. 2021-09-27: [Microbiome tutorial day five](Fall2021/tutorials/2021-09-27_microbiome_Day5.html), plus supplemental code for [taxonomic identification](Fall2021/tutorials/2021_09_27_microbiome_supp_taxaID.html).
